### ISSUE TITLE
Оголошення змінних

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#1]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/529cc13cff549f2f0129787b3d2af62950cdbc30/js/functions.js#L55
- не забуваємо оголошувати змінні. Неоголошені змінні - джерело потенційних помилок і погіршують відтримку коду.

**Comment by BohdanLuts** [comment]
Добре. Виправлено.
