### ISSUE TITLE
друга реалізація

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#10]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/87a028daf4a65549cd292c4b748213e9fbcba1b0/js/closure.js#L29
- відпрацьовує все коректно👍. Єдине, можна подумати над іменами параметрів (і над let).

**Comment by BohdanLuts** [comment]
Змінив назви на більш логічні
