### ISSUE TITLE
номер телефону

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#2]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/d17b173fb9ca81f6c43584dacf376b754a0f48c6/js/objects.js#L22
- номер телефону навіть потенційно не буде брати участь в арифметичних обчисленнях, його доцільно робити рядком.

**Comment by BohdanLuts** [comment]
Згоден. Виправляю.
