### ISSUE TITLE
Перебір парних чисел

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#3]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/14c0cdbc52287dc730e6724e1f1b1331f73dca65/js/array.js#L30
- `0` також є парним числом (стосується також рядка 41).
- щоб уникнути додаткових перевірок, доцільно було б лічильник інкрементувати на `2`.

**Comment by BohdanLuts** [comment]
Виправлено
