### ISSUE TITLE
кількість нульових елементів

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#4]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/14c0cdbc52287dc730e6724e1f1b1331f73dca65/js/array.js#L59
- спробуйте протестувати дану функцію на масиві з кількістю нульових елементів, більше 1. Тут важливо врахувати області видимості, а також варто приберати консолелоги з функції, якщо тільки логування не є її основною метою (гарною практикою є розробка функцій з єдиною відповідальністю. Тут функція має повернути значення, а далі можна його виводити, використовувати в розрахунках тощо).

**Comment by BohdanLuts** [comment]
Протестовано. Переписав, працює корректно.
