### ISSUE TITLE
наявність елемента, що видаляється

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#7]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/87a028daf4a65549cd292c4b748213e9fbcba1b0/js/usersArray.js#L56
- було б плюсом перевірити, чи є такий елемент (за критерієм, що повертає findIndex, якщо не знаходить елемент), інакше може очікувати нєжданчік)

**Comment by BohdanLuts** [comment]
Зрозумів навіщо. Перероблено.
