### ISSUE TITLE
можливі методи

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-14-JS#8]
https://github.com/BohdanLuts/home-work-lesson-14-JS/blob/87a028daf4a65549cd292c4b748213e9fbcba1b0/js/usersArray.js#L66
- згодна з варіантом. Ремарка: також можна використовувати some або find, тоді умова буде коротша

**Comment by BohdanLuts** [comment]
Дописав, протестував на інших емейлах
